"""`python -m sglang.benchmark.serving` (SGLang v0.5.21) as a Loom load generator.

Flags and result fields are those of `python/sglang/benchmark/serving.py` and
`python/sglang/benchmark/datasets/` at the v0.5.21 tag. It drives any
OpenAI-compatible server: backend `sglang-oai[-chat]` against SGLang, `vllm[-chat]`
otherwise (same request code; the SGLang names also read `/server_info`).

Workloads: `synthetic` -> `random-ids` (random token ids, no ShareGPT download)
and `shared_prefix` -> `generated-shared-prefix` (prompts generated by SGLang);
chat-endpoint kinds replay the Loom requests through the `openai` dataset, which
keeps file order and passes `messages` through unchanged. Completions-endpoint
kinds other than `synthetic` have no order-preserving dataset and are rejected.
Arrivals: Poisson only. The tool ignores EOS unless `--disable-ignore-eos`.

Its JSONL result has no per-request start times or latencies, so its timeline is
"unavailable": records are placed at t=0 and end at their last content chunk.
On the completions endpoint the output length is the requested `max_tokens`
(asking for a usage chunk there crashes the tool's parser).
"""

from __future__ import annotations

import json
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from loom_bench.loadgen.arrivals import GammaArrivals, PoissonArrivals
from loom_bench.loadgen.base import RunResult
from loom_bench.loadgen.external import (
    ExternalLoadGenerator,
    ToolRun,
    UnsupportedByTool,
    ignore_eos,
    read_result,
    result_from_arrays,
    shared_prefix_lengths,
    split_base_url,
    tool_summary,
    write_jsonl,
)
from loom_bench.records import LoadMode
from loom_bench.workloads.profiles import SharedPrefixProfile, SyntheticProfile

NAME = "sglang_bench"

_BACKENDS = {
    True: {"completions": "sglang-oai", "chat": "sglang-oai-chat"},
    False: {"completions": "vllm", "chat": "vllm-chat"},
}
_SUMMARY_KEYS = (
    "duration",
    "completed",
    "request_throughput",
    "output_throughput",
    "total_throughput",
    "max_concurrent_requests",
)


class SglangBench:
    name = NAME
    result_file = "result.jsonl"

    def __init__(
        self, executable: Sequence[str] = ("python3", "-m", "sglang.benchmark.serving")
    ) -> None:
        self.executable = list(executable)

    def build_argv(self, run: ToolRun, result_path: Path) -> list[str]:
        root, prefix = split_base_url(run.job.base_url)
        if prefix != "/v1":
            raise UnsupportedByTool(
                f"sglang bench_serving always calls /v1/...; base_url must end in /v1, "
                f"got {run.job.base_url!r}"
            )
        endpoint = run.profile.endpoint
        argv = [
            *self.executable,
            "--backend", _BACKENDS[run.job.engine == "sglang"][endpoint],
            "--base-url", root,
            "--model", run.job.served_model,
        ]  # fmt: skip
        if run.tokenizer:
            argv += ["--tokenizer", run.tokenizer]
        argv += [
            "--num-prompts", str(run.num_prompts),
            "--seed", str(run.job.seed),
            "--warmup-requests", str(run.warmup_requests),
            *self._load_args(run),
            *self._dataset_args(run),
        ]  # fmt: skip
        if not ignore_eos(run.profile):
            argv.append("--disable-ignore-eos")
        body: dict[str, Any] = {"temperature": run.profile.temperature, **run.job.extra_body}
        if endpoint == "chat":
            body["stream_options"] = {"include_usage": True}
        argv += [
            "--extra-request-body", json.dumps(body, sort_keys=True),
            "--output-file", str(result_path),
            "--output-details",
            "--disable-tqdm",
        ]  # fmt: skip
        return argv

    def parse(self, run: ToolRun, result_path: Path) -> RunResult:
        data = read_result(result_path, NAME, jsonl=True)
        source = "server_usage" if run.profile.endpoint == "chat" else "requested"
        meta = {"tool_summary": tool_summary(data, _SUMMARY_KEYS), "output_lens_source": source}
        return result_from_arrays(run, data, tool=NAME, meta=meta)

    def _load_args(self, run: ToolRun) -> list[str]:
        if run.mode is LoadMode.CLOSED_LOOP:
            return ["--request-rate", "inf", "--max-concurrency", str(run.concurrency)]
        arrival = run.ctx.arrival
        match arrival:
            case PoissonArrivals():
                rate = arrival.rate
            case GammaArrivals() if arrival.burstiness == 1:
                rate = arrival.rate
            case _:
                kind = getattr(arrival, "kind", None)
                raise UnsupportedByTool(
                    f"sglang bench_serving only generates Poisson arrivals, not {kind}"
                    + (" with burstiness != 1" if kind == "gamma" else "")
                    + "; use vllm_bench or the native generator"
                )
        return ["--request-rate", str(float(rate)), "--max-concurrency", str(run.concurrency)]

    def _dataset_args(self, run: ToolRun) -> list[str]:
        p = run.profile
        if isinstance(p, SyntheticProfile):
            input_len, output_len, ratio = random_ids_lengths(p)
            return [
                "--dataset-name", "random-ids",
                "--random-input-len", str(input_len),
                "--random-output-len", str(output_len),
                "--random-range-ratio", str(ratio),
            ]  # fmt: skip
        if isinstance(p, SharedPrefixProfile):
            prefix, question, output = shared_prefix_lengths(p, "sglang bench_serving")
            return [
                "--dataset-name", "generated-shared-prefix",
                "--gsp-num-groups", str(p.num_prefix_groups),
                "--gsp-prompts-per-group", str(run.num_prompts // p.num_prefix_groups),
                "--gsp-system-prompt-len", str(prefix),
                "--gsp-question-len", str(question),
                "--gsp-output-len", str(output),
                "--gsp-range-ratio", "1.0",
            ]  # fmt: skip
        if p.endpoint != "chat":
            raise UnsupportedByTool(
                f"sglang bench_serving replays Loom prompts only on the chat endpoint "
                f"(openai dataset); {p.name} ({p.kind}) uses completions"
            )
        write_openai_dataset(run)
        return ["--dataset-name", "openai", "--dataset-path", str(run.dataset_path)]


def random_ids_lengths(p: SyntheticProfile) -> tuple[int, int, float]:
    """`--random-input-len`, `--random-output-len`, `--random-range-ratio` for `p`.

    SGLang samples lengths uniformly from [len * ratio, len]; Loom's range_ratio r
    means [len * (1 - r), len * (1 + r)]. So len = base * (1 + r) and
    ratio = (1 - r) / (1 + r), which matches to within one token at the low end.
    """
    r = p.range_ratio
    if not r:
        return p.input_len, p.output_len, 1.0
    return int(p.input_len * (1 + r)), int(p.output_len * (1 + r)), (1 - r) / (1 + r)


def write_openai_dataset(run: ToolRun) -> None:
    """SGLang `openai` rows: the native request body. `max_tokens` becomes the output
    length and the other fields (temperature, ignore_eos) are sent per request;
    ignore_eos is written out because the tool defaults it to true."""
    rows = [
        {**req.payload, "ignore_eos": bool(req.payload.get("ignore_eos", False))}
        for req in run.requests
    ]
    write_jsonl(run.dataset_path, rows)


def generator() -> ExternalLoadGenerator:
    return ExternalLoadGenerator(SglangBench())
